services:
  - type: web
    name: team-calendar
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: NODE_ENV
        value: production