name: Auto Version Bump

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Bump version
      run: npm run version:bump
      
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json src/version.json
        git diff --staged --quiet || git commit -m "chore: bump version [skip ci]"
        git push